name: Swift-macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: Swift build
      run: swift build -v
    - name: Cache Bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-
    - name: bundle install
      run: bundle install --deployment

    - name: pod lib lint
      run: bundle exec pod lib lint