name: Swift-macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    
    - name: Swift build
      run: swift build -v
    
    - name: Bundle install
      run: bundle install

    - name: Pod lib lint
      run: make podLibLint